# Generated by Django 4.0.3 on 2022-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_faculty_district_faculty_house_no_faculty_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='aadhar_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
