# Generated by Django 4.0.3 on 2022-11-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_faculty_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='aadhar_no',
            field=models.CharField(max_length=12),
        ),
    ]
