# Generated by Django 4.0.3 on 2022-11-17 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_faculty_college_faculty_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='article_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='award',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='cost_of_project',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='faculty',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='issn_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='journal_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='journal_vol',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='org_award',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='project_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='faculty',
            name='year_award',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='year_of_publication',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
