# Generated by Django 4.0.3 on 2022-11-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_rename_org_award_faculty_org_of_award_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='org_of_award',
            new_name='organisation_of_award',
        ),
    ]
