# Generated by Django 4.0.3 on 2022-11-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_rename_org_of_award_faculty_organisation_of_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='journal_name',
            new_name='publication_journal_name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='journal_vol',
            new_name='publication_journal_vol',
        ),
    ]
