# Generated by Django 4.0.3 on 2022-11-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_rename_journal_name_faculty_publication_journal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='locality',
            field=models.CharField(default='unspecified', max_length=100),
        ),
    ]
